export enum CommandResponse {
  Incomplete = 'Incomplete',
  Ok = 'Ok',
  Help = 'Help',
  WrongInput = 'WrongInput',
  UsernameNotSet = 'UsernameNotSet',
  NotFound = 'NotFound',
  NotSupportedInDm = 'NotSupportedInDm',
  Error = 'Error',
  NoScrobbles = 'NoScrobbles',
  NoPermission = 'NoPermission',
  Cooldown = 'Cooldown',
  IndexRequired = 'IndexRequired',
  LastFmError = 'LastFmError',
  Disabled = 'Disabled',
  Censored = 'Censored',
  UserBlocked = 'UserBlocked',
  RateLimited = 'RateLimited',
  SupporterRequired = 'SupporterRequired',
  OnlySupportedInDm = 'OnlySupportedInDm',
  PremiumServerRequired = 'PremiumServerRequired',
  Deleted = 'Deleted',
}
